{{- if .Values.aasDiscovery.enabled -}}
{{- include "basyx.service.deployment" (dict
  "root" .
  "component" "aasDiscovery"
  "nameSuffix" "aas-discovery"
  "fullnameHelper" "basyx-aasDiscovery.fullname"
  "labelsHelper" "basyx-aasDiscovery.labels"
  "selectorLabelsHelper" "basyx-aasDiscovery.selectorLabels"
  "serviceAccountHelper" "basyx-aasDiscovery.serviceAccountName"
  "containerName" "aas-discovery"
  "extraEnv" (include "basyx.service.extraEnvMap" (.Values.aasDiscovery.environment | default dict))
) -}}
{{- end }}
