{{- if .Values.aasDiscovery.enabled -}}
{{- if .Values.aasDiscovery.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "basyx-aasDiscovery.fullname" . }}
  labels:
    {{- include "basyx-aasDiscovery.labels" . | nindent 4 }}
  annotations: &commonIngressAnnotations
  {{- include "common.ingressTLS.annotations" . | nindent 2}}
  {{- with .Values.aasDiscovery.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.aasDiscovery.ingress.className | quote }}
  {{- include "common.ingressTLS" . | indent 2}}
  rules:
    {{- range .Values.aasDiscovery.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ tpl .path $ | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "basyx-aasDiscovery.fullname" $ }}
                port:
                  number: {{ $.Values.aasDiscovery.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}