{{- if eq (include "database.managed" .) "true" -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{.Values.database.clusterName | default "basyx-database" }}
  labels:
    {{- include "basyx.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.database.instances }}
  primaryUpdateStrategy: unsupervised
  storage:
    size: {{ .Values.database.storage.size }}
  bootstrap:
    initdb:
      database: {{.Values.database.database | default "basyx" }}
      owner: {{.Values.database.owner | default "basyx" }}

{{- end }}
