{{- if eq (include "database.poolerEnabled" .) "true" -}}
{{- include "database.poolerResource" (dict "root" . "pooler" .Values.database.pooler "name" (include "database.poolerName" .) "type" "rw") }}
{{- end }}
{{- if eq (include "database.readOnlyPoolerEnabled" .) "true" }}
---
{{ include "database.poolerResource" (dict "root" . "pooler" .Values.database.reader.pooler "name" (include "database.readOnlyPoolerName" .) "type" "ro") }}
{{- end }}
