#################################################################################
 # Copyright (C) 2025 the Eclipse BaSyx Authors
 # Copyright (C) 2025 SAP SE
 #
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
 # "Software"), to deal in the Software without restriction, including
 # without limitation the rights to use, copy, modify, merge, publish,
 # distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so, subject to
 # the following conditions:
 #
 # The above copyright notice and this permission notice shall be
 # included in all copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 # NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 # LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 # WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #
 # SPDX-License-Identifier: MIT
#################################################################################

---
imagePullSecrets: []

# Enabled by default
enabled: true

image: 
  name: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
  pullPolicy: IfNotPresent

resources: {}
podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  host: aas-discovery.local

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

apirule:
  enabled: false
  host: aas-discovery.local
  methods: 
    - "GET" 
    - "HEAD" 
    - "POST" 
    - "PUT" 
    - "DELETE" 
    - "CONNECT" 
    - "OPTIONS" 
    - "TRACE"
    - "PATCH"
  # -- Allows configuring CORS headers sent with the response. If corsPolicy is not defined, the CORS headers are enforced to be empty.
  corsPolicy: 
    allowMethods:
    - POST
    - GET
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
    allowOrigins:
      - regex: ".*" # allow all origins
    allowCredentials: true

# Content of application.properties
config: |
  spring.application.name=AAS Discovery Service

  basyx.aasdiscoveryservice.name=aas-discovery-service

  basyx.backend=MongoDB
  spring.data.mongodb.host=mongo
  spring.data.mongodb.database=aas-discovery
  spring.data.mongodb.authentication-database=admin
  spring.data.mongodb.username=mongoAdmin
  spring.data.mongodb.password=mongoPassword

  basyx.cors.allowed-origins=*
  basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD

  basyx.feature.authorization.enabled = true
  basyx.feature.authorization.type = rbac
  basyx.feature.authorization.jwtBearerTokenProvider = keycloak
  basyx.feature.authorization.rbac.file = file:/application/rbac_rules.json
  spring.security.oauth2.resourceserver.jwt.issuer-uri= http://keycloak.basyx.local:8080/realms/BaSyx

rbac: 
  rules: |
    [
      {
        "role": "basyx-assetid-creator",
        "action": "CREATE",
        "targetInformation": {
          "@type": "aas-discovery-service",
          "aasIds": "*",
          "assetIds": []
        }
      },
      {
        "role": "basyx-assetid-discoverer",
        "action": "READ",
        "targetInformation": {
          "@type": "aas-discovery-service",
          "aasIds": "*",
          "assetIds": []
        }
      },
      {
        "role": "basyx-assetid-deleter",
        "action": "DELETE",
        "targetInformation": {
          "@type": "aas-discovery-service",
          "aasIds": "*",
          "assetIds": []
        }
      },
      {
        "role": "basyx-aas-discoverer",
        "action": "READ",
        "targetInformation": {
          "@type": "aas-discovery-service",
          "aasIds": null,
          "assetIds": [
            {
              "name": "*",
              "value": "*"
            }
          ]
        }
      }
    ]
