{{- if .Values.companyLookup.enabled -}}
{{- include "basyx.service.deployment" (dict
  "root" .
  "component" "companyLookup"
  "nameSuffix" "company-lookup"
  "fullnameHelper" "basyx-companyLookup.fullname"
  "labelsHelper" "basyx-companyLookup.labels"
  "selectorLabelsHelper" "basyx-companyLookup.selectorLabels"
  "serviceAccountHelper" "basyx-companyLookup.serviceAccountName"
  "containerName" "company-lookup"
) -}}
{{- end }}
