#################################################################################
 # Copyright (C) 2025 the Eclipse BaSyx Authors
 # Copyright (C) 2025 SAP SE
 #
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
 # "Software"), to deal in the Software without restriction, including
 # without limitation the rights to use, copy, modify, merge, publish,
 # distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so, subject to
 # the following conditions:
 #
 # The above copyright notice and this permission notice shall be
 # included in all copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 # NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 # LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 # WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #
 # SPDX-License-Identifier: MIT
#################################################################################

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aas-web-ui.fullname" . }}
  labels:
    {{- include "aas-web-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aas-web-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- if .Values.apirule.enabled }}
        sidecar.istio.io/inject: "true"
        {{ end -}}
        {{- include "aas-web-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ .Values.image.name }}      
        env:
        - name: AAS_REPO_PATH
          value: {{ .Values.config.aasRepoUrl | quote }}
        - name: SUBMODEL_REPO_PATH
          value: {{ .Values.config.aasSubmodelsRepoUrl | quote }}
        - name: CD_REPO_PATH
          value: {{ .Values.config.conceptdescriptionRepoUrl | quote }}
        - name: AAS_DISCOVERY_PATH
          value: {{ .Values.config.aasDiscoveryUrl | quote }}
        - name: AAS_REGISTRY_PATH
          value: {{ .Values.config.aasRegistryUrl | quote }}
        - name: SUBMODEL_REGISTRY_PATH
          value: {{ .Values.config.submodelRegistryUrl | quote }}
        - name: KEYCLOAK_URL
          value: {{ .Values.config.keycloakUrl }}
        - name: KEYCLOAK_REALM
          value: {{ .Values.config.keycloakRealm }}
        - name: KEYCLOAK_CLIENT_ID
          value: {{ .Values.config.keycloakClientId }}
        # - name: CHOCKIDAR_USEPOLLING
        #   value: "true"
        # - name: VITE_PRIMARY_COLOR
        #   value: blue
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.logo.relativePath }}
        - mountPath: /app/src/assets/
          name: {{ template "aas-web-ui.fullname" $ }}-config
        {{- end }}
        {{- if .Values.externalPlugins.enabled }}
        - mountPath: /app/src/UserPlugins/
          name: plugins-volume
        {{- end }}
      restartPolicy: Always
      volumes:
      {{- if .Values.logo.relativePath }}
      - name: {{ template "aas-web-ui.fullname" $ }}-logo
        configMap:
          name: {{ template "aas-web-ui.fullname" $ }}-logo
      {{- end }}
      {{- if .Values.externalPlugins.enabled }}
      - name: plugins-volume
        projected:
          sources:
          {{- range $index, $element := .Values.externalPlugins.plugins }}
            - configMap:
                name: {{ $element.configMapName }}
                items:
                  - key: {{ $element.fileName }}
                    path: {{ $element.fileName }}
          {{- end }}
      {{- end }}
