{{- if .Values.dppApi.enabled -}}
{{- if .Values.dppApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basyx-dppApi.serviceAccountName" . }}
  labels:
    {{- include "basyx-dppApi.labels" . | nindent 4 }}
  {{- with .Values.dppApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.dppApi.serviceAccount.automount }}
{{- end }}
{{- end }}
