{{- if .Values.keycloak.enabled -}}
{{- if .Values.keycloak.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basyx-keycloak.serviceAccountName" . }}
  labels:
    {{- include "basyx-keycloak.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.keycloak.serviceAccount.automount }}
{{- end }}
{{- end }}