{{- if .Values.keycloak.enabled }}
--- 
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.keycloak.secrets.name }}
  namespace: {{ .Release.Namespace }}
stringData:
  admin: {{ .Values.keycloak.secrets.admin.username | quote }}
  adminPassword: {{ .Values.keycloak.secrets.admin.password | quote }}
  clientName: {{ .Values.keycloak.secrets.client.name | quote }}
  clientPassword: {{ .Values.keycloak.secrets.client.clientPassword | quote }}
{{ end }}
