{{- if .Values.aasEnvironment.enabled -}}
{{- if .Values.aasEnvironment.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "basyx-aasEnvironment.fullname" . }}
  labels:
    {{- include "basyx-aasEnvironment.labels" . | nindent 4 }}
  {{- with .Values.aasEnvironment.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- include "common.httpRoute.parentRefs" (dict "root" $ "parentRefs" .Values.aasEnvironment.httpRoute.parentRefs) | nindent 4 }}
  hostnames:
    {{- range .Values.aasEnvironment.httpRoute.hosts }}
    - {{ tpl .host $ | quote }}
    {{- end }}
  rules:
    {{- range .Values.aasEnvironment.httpRoute.hosts }}
    {{- range .paths }}
    - matches:
        - path:
            type: {{ .pathType }}
            value: {{ tpl .path $ | quote }}
      backendRefs:
        - name: {{ include "basyx-aasEnvironment.fullname" $ }}
          port: {{ $.Values.aasEnvironment.service.port }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
