{{- if .Values.aasEnvironment.enabled -}}
{{- if .Values.aasEnvironment.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "basyx-aasEnvironment.fullname" . }}
  labels:
    {{- include "basyx-aasEnvironment.labels" . | nindent 4 }}
  {{- include "common.ingress.metadataAnnotations" (dict "root" . "ingress" .Values.aasEnvironment.ingress) | nindent 2 }}
spec:
  {{- include "common.ingress.className" (dict "root" . "ingress" .Values.aasEnvironment.ingress) | nindent 2 }}
  {{- include "common.ingressTLS" . | nindent 2 }}
  rules:
    {{- range .Values.aasEnvironment.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ tpl .path $ | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "basyx-aasEnvironment.fullname" $ }}
                port:
                  number: {{ $.Values.aasEnvironment.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
