{{- if and .Values.aasWebGui.enabled .Values.aasWebGui.secretEnvironment (not .Values.aasWebGui.existingSecretEnvironment) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "basyx-aasWebGui.fullname" . }}-secret
  labels:
    {{- include "basyx-aasWebGui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.aasWebGui.secretEnvironment }}
  {{ $key }}: {{ tpl (print $value) $ | quote }}
  {{- end }}
{{- end }}
